### ISSUE TITLE
Hyphenated numbers are not fully ignored

### ISSUE THREAD

**Issue by vaneseltine** [vaneseltine/nominally#52]
```
ɪ (.venv) nominally › python -m nominally "14,A,A"
       raw: 14,A,A
   cleaned: {'14, a, a'}
    parsed: a, a
      list: ['', 'a', '', 'a', '', '']
     title:
     first: a
    middle:
      last: a
    suffix:
  nickname:
ɪ (.venv) nominally › python -m nominally "1-4,A,A"
       raw: 1-4,A,A
   cleaned: {'1-4, a, a'}
    parsed: a a
      list: ['', 'a', 'a', '', '', '']
     title:
     first: a
    middle: a
      last:
    suffix:
  nickname:
```

This was found via [hypothesis](https://hypothesis.readthedocs.io/en/latest/) generating ```"¼,A,A"```
